name: purequiz_demo
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  isar: 3.0.5 
  isar_flutter_libs: 3.0.5
  cupertino_icons: ^1.0.2
  path_provider: 2.0.15
  share_plus: ^6.3.0
  flutter_animate: ^4.2.0+1
  logger: ^1.4.0
  document_file_save_plus: ^2.0.0
  flutter_document_picker: ^5.2.3
  shimmer: ^3.0.0
  animations: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: 3.0.5
  build_runner: any

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/avatar_logo.png
    - assets/placeholder_image.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  